print('olá, me diga seu nome, idade e peso\n')
nome = input('qual seu nome? ')
idade = int(input('qual sua idade? '))
peso = float(input('qual seu peso? '))
print('olá,', nome, 'sua idade é', idade, 'seu peso é', peso)
print('a soma do seu peso com a idade é', peso + idade )